### ISSUE TITLE
Fart Gen duplicates with pickaxe

### ISSUE THREAD

**Issue by happybandit360** [HurtsAsHell/FartGeneratorPublic#1]
**Describe the bug**
Fart Generator duplicates if broken with a pick

**To Reproduce**
Place fart generator, break with pick, get 2 fart gens

**Expected behavior**
You only get 1 fart generator when broken

**Screenshots**
https://clips.twitch.tv/SavoryPerfectCucumberPipeHype

**Versions:** _DO NOT write "the latest"_
- Fart Energy Generator : cowgen-0.1.0.jar
- Other mods that aren't in the initial modpack:  https://docs.google.com/spreadsheets/d/1I8AXaK1kuXGS9vD2Qa2wAgXuu2uauyAl6SZTFqudUwQ/edit#gid=0

**Crash Report** _if avaliable_ 
**Use [gist](https://gist.github.com) or spoilers or [paste.ee](https://paste.ee) or [pastebin](https://pastebin.com)**

**Log** _if needed_
**Use [gist](https://gist.github.com) or spoilers or [paste.ee](https://paste.ee) or [pastebin](https://pastebin.com)**

**Additional context**

**Comment by HurtsAsHell** [comment]
MH, weird, i will work on it. Thanks for the report and sorry if i have answar you only now

**Comment by HurtsAsHell** [comment]
Fixed, i will release the next version asap
