### ISSUE TITLE
Multiple mobs and output

### ISSUE THREAD

**Issue by happybandit360** [HurtsAsHell/FartGeneratorPublic#2]
**Describe the solution you'd like**
I would love to see the ability to place multiple mobs that provide different outputs

**Describe alternatives you've considered**
For example, we set a chicken to provide 5rf/t, a pig does 10 rf/t, a cow does 20rf/t for example.

**Why would you like this to be implemented?**
To add fun and variety to our pack

**Additional context**
GenerikB describing the idea -  https://clips.twitch.tv/IncredulousKitschyLadiesTBTacoLeft

**Comment by HurtsAsHell** [comment]
Yes' it's a good idea and i want to create it asap. Thanks for the suggestion

**Comment by HurtsAsHell** [comment]
I did it but I need testing, could you be my tester for this time?

**Comment by happybandit360** [comment]
We'd be happy to help

**Comment by HurtsAsHell** [comment]
If you write me in pvt on discord, i will share you the testing version of the mod
